ALTER TABLE "Employee" ALTER COLUMN "tenantId" SET NOT NULL;

-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "branch" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "storeTiming" DROP NOT NULL,
ALTER COLUMN "offDay" DROP NOT NULL,
ALTER COLUMN "isDeleted" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL;
